apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  labels:
    app.kubernetes.io/name: eda
    app.kubernetes.io/instance: eda-sample
    app.kubernetes.io/part-of: eda-server-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: eda-server-operator
  name: eda-sample
spec:
  automation_server_url: https://your-ascender-or-awx-host
  no_log: true
  image_pull_policy: IfNotPresent
  service_type: ClusterIP
